#!/usr/bin/python
# -*- coding: utf-8 -*-
from natconfig import *
from robot.libraries.BuiltIn import BuiltIn
from robot.api import logger

''' 流配置接口，以OVS的配置为基准进行配置：
        https://www.man7.org/linux/man-pages/man7/ovs-fields.7.html
'''

class JaguarConfig():
    def __init__(self):
        #使用chaconfig来配置 
        self.value = {
            "input_port_rx" : {
                "tbl_name": "input_port_rx",
                "key" :  {
                    "INPUT_PORT_RX_TUNNEL_PKT_FLAG" : 0,
                    "INPUT_PORT_RX_SRC_PORT" :  0
                },
                "table" : {
                    "INPUT_PORT_RX_DEF_ACT_INDEX": 0,#默认到0口
                    "INPUT_PORT_RX_OP_CODE": 4,  # 2 to classify ,4 dorp
                    "INPUT_PORT_RX_MEP_DSTRIBUT_PROF": 0,
                    "INPUT_PORT_RX_MEP_DSPTCH_TYPE": 0,
                    "INPUT_PORT_RX_RSV": 0,
                    "INPUT_PORT_RX_ACT_TYPE": 0,
                    "INPUT_PORT_RX_DEF_DST": 0,
                    "INPUT_PORT_RX_MIRR_PRI": 0,
                    "INPUT_PORT_RX_MIRR_METER_IDX": 0,
                    "INPUT_PORT_RX_MIRR_IDX": 0,
                    "INPUT_PORT_RX_METE_INFO0": 0,
                    "INPUT_PORT_RX_GROUP_IDX": 0
                }
            },
            "default_action" :{
                "index":0,
                "tbl_name": "default_action",
                "table":{
                    "PRIORITY":0,
                    "VERSION0":0,
                    "VERSION1":0,
                    "VERSION2":0,
                    "VERSION3":0,
                    "VER_GROUP0":0,
                    "VER_GROUP1":0,
                    "VER_GROUP2":0,
                    "VER_GROUP3":0,
                    "RANG_INDEX0":0,
                    "RANG_INDEX1":0,
                    "STATS_SAME_IDX":0,
                    "STATISTICS":0,
                    "CMD_QUEUE_ID":0,
                    "AGE_MOD":0,
                    "ECMP_ENABLE":0,
                    "ECMP_ENTRY_NUM":0,
                    "TSE_RSV":0,
                    "EX_RESULT_INDEX":0,
                    "TSE_EXT_RESULT_LEN":0,
                    "PIPE_EXT_RESULT_LEN":0,
                    "OPCODE":0,
                    "KEYBUILD_PROFILE_ID":0,
                    "STORAGE_READ":0,
                    "GROUP_STATS_INDEX":0,
                    "MEP_DISTRI_PROF":0,
                    "MEP_DISPATCH_TYPE":0,
                    "SOURCE_TABLE":0,
                    "SET_TC_ENABLE":0,
                    "SET_TC_VALUE":0,
                    "DESTINATION_VALID":1,
                    "ACTION_TYPE":0,
                    "DESTINATION":128,
                    "DECAPSULATION":0,
                    "MIRROR_PRI":0,
                    "MIRROR_METER_INDEX":0,
                    "MIRRORING":0,
                    "EXT_BIT_MAP":0,
                    "METER_NUM":0,
                    "METADATA_UPDATE":0,
                    "REPLACE_L4_DPORT":0,
                    "REPLACE_L4_SPORT":0,
                    "REPLACE_DIPV4":0,
                    "REPLACE_SIPV4":0,
                    "REPLACE_DIPV6":0,
                    "REPLACE_SIPV6":0,
                    "TTL_UPDATE":0,
                    "TOS_UPDATE":0,
                    "REMOVE_OUTER_VLAN":0,
                    "REMOVE_INNER_VLAN":0,
                    "REPLACE_INNER_VLAN":0,
                    "REPLACE_OUTER_VLAN":0,
                    "REPLACE_SMAC":0,
                    "REPLACE_DMAC":0,
                    "DEC_NSH_TTL":0,
                    "INT_TUNNEL_DELETE":0,
                    "UPDATE_FIELD":0,
                    "TUNNEL_ENCAP_TYPE":0,
                    "TUNNEL_ENCAP_LEN":0,
                    "L4_ENCAP_TYPE":0,
                    "L3_ENCAP_TYPE":0,
                    "VTAG_TYPE":0,
                    "L2_FLAG":0,
                    "ECN_INHERIT_TO_INNER":0,
                    "ECN_INHERIT_TO_OUTER":0,
                    "data":[]
                }
            },
            "classify" : {
                "tbl_name": "classify",
                "tbl_id": 0,
                "tbl_pipe": 0,
                "priority": 0,
                "key": {
                    "CLASSIFY1_PKT_TYPE": 0,
                    "CLASSIFY1_PKT_ERROR_FLAG": 0,
                    "CLASSIFY1_PKT_ERROR_TYPE": 0,
                    "CLASSIFY1_GROUP_INDEX": 0,
                    "CLASSIFY1_OUT_TUNNEL_TYPE": 0,
                    "CLASSIFY1_OUT_L5P5_HEAD_TYPE": 0,
                    "CLASSIFY1_INNER_TUNNEL_TYPE": 0,
                    "CLASSIFY1_INNER_L5P5_HEAD_TYPE": 0,
                    "CLASSIFY1_TUNNEL_ID": 0,
                    "CLASSIFY1_ADDRESS0": 0,
                    "CLASSIFY1_ADDRESS1": 0,
                    "CLASSIFY1_ADDRESS_EXTEND": 0,
                    "CLASSIFY1_OUT_VLAN_VALID": 0,
                    "CLASSIFY1_INNER_VLAN_VALID": 0,
                    "CLASSIFY1_OUT_VLAN_ID": 0,
                    "CLASSIFY1_OUT_VLAN_TPID": 0,
                    "CLASSIFY1_INNER_VLAN_ID": 0,
                    "CLASSIFY1_INNER_VLAN_TPID": 0,
                    "CLASSIFY1_ETH_TYPE": 0,
                    "CLASSIFY1_RSV1": 0,
                    "CLASSIFY1_RSV2": 0,
                    "CLASSIFY1_PIPE_ID": 0
                },
                "mask": {
                    "CLASSIFY1_PKT_TYPE": 0,
                    "CLASSIFY1_PKT_ERROR_FLAG": 0,
                    "CLASSIFY1_PKT_ERROR_TYPE": 0,
                    "CLASSIFY1_GROUP_INDEX": 0,
                    "CLASSIFY1_OUT_TUNNEL_TYPE": 0,
                    "CLASSIFY1_OUT_L5P5_HEAD_TYPE": 0,
                    "CLASSIFY1_INNER_TUNNEL_TYPE": 0,
                    "CLASSIFY1_INNER_L5P5_HEAD_TYPE": 0,
                    "CLASSIFY1_TUNNEL_ID": 0,
                    "CLASSIFY1_ADDRESS0": 0,
                    "CLASSIFY1_ADDRESS1": 0,
                    "CLASSIFY1_ADDRESS_EXTEND": 0,
                    "CLASSIFY1_OUT_VLAN_VALID": 0,
                    "CLASSIFY1_INNER_VLAN_VALID": 0,
                    "CLASSIFY1_OUT_VLAN_ID": 0,
                    "CLASSIFY1_OUT_VLAN_TPID": 0,
                    "CLASSIFY1_INNER_VLAN_ID": 0,
                    "CLASSIFY1_INNER_VLAN_TPID": 0,
                    "CLASSIFY1_ETH_TYPE": 0,
                    "CLASSIFY1_RSV1": 0,
                    "CLASSIFY1_RSV2": 0,
                    "CLASSIFY1_PIPE_ID": 0
                }, "table":
                {
                    "CLASSIFY1_OPRATE_CODE": 0,
                    "CLASSIFY1_DEFAULT_ACTION_INDEX": 0,
                    "CLASSIFY1_KEY_BUILD_PROFILE_ID": 0,
                    "CLASSIFY1_DISTRIBUTE_MODE": 0,
                    "CLASSIFY1_DISPATCH_TYPE": 0,
                    "CLASSIFY1_DEFAULT_DEST_VALID": 0,
                    "CLASSIFY1_DEFAULT_DEST_ACT_TYPE": 0,
                    "CLASSIFY1_DEFAULT_DEST": 0,
                    "CLASSIFY1_RESET_TC_FLAG": 0,
                    "CLASSIFY1_TC_VALUE": 0
                }
            },
            "profile" : {
                "tbl_name": "profile",
                "tbl_id": 0,
                "tbl_pipe": 0,
                "priority": 0,
                "key": {
                    "PROFILE_GROUP_INDEX": 0,
                    "PROFILE_KEY_BUILD_PROFILE_ID": 0,
                    "PROFILE_L4_DST_PORT": 0,
                    "PROFILE_L4_IS_TCPUDP": 0,
                    "PROFILE_L4_HD_TYPE": 0,
                    "PROFILE_L4_HD_VALID": 0,
                    "PROFILE_L3P5_HD_TYPE": 0,
                    "PROFILE_L3P5_VALID": 0,
                    "PROFILE_L3_IS_IP": 0,
                    "PROFILE_L3_HD_TYPE": 0,
                    "PROFILE_L3_HD_VALID": 0,
                    "PROFILE_L2P5_SUBTYPE": 0,
                    "PROFILE_L2P5_HD_TYPE": 0,
                    "PROFILE_L2P5_HD_VALID": 0,
                    "PROFILE_INNER_VLAN_TAG": 0,
                    "PROFILE_OUT_VLAN_TAG": 0,
                    "PROFILE_MAC_TYPE": 0,
                    "PROFILE_L2_HD_VALID": 0,
                    "PROFILE_TL_L5P5_HD_TYPE": 0,
                    "PROFILE_TL_L5P5_HD_VALID": 0,
                    "PROFILE_TL_TUNNEL_FLAGS": 0,
                    "PROFILE_TL_TUNNEL_TYPE": 0,
                    "PROFILE_TL_TUNNEL_VALID": 0,
                    "PROFILE_TL_L4_IS_TCPUDP": 0,
                    "PROFILE_TL_L4_HD_TYPE": 0,
                    "PROFILE_TL_L4_HD_VALID": 0,
                    "PROFILE_TL_L3P5_HD_TYPE": 0,
                    "PROFILE_TL_L3P5_VALID": 0,
                    "PROFILE_TL_L3_IS_IP": 0,
                    "PROFILE_TL_L3_HD_TYPE": 0,
                    "PROFILE_TL_L3_HD_VALID": 0,
                    "PROFILE_TL_L2P5_SUBTYPE": 0,
                    "PROFILE_TL_L2P5_HD_TYPE": 0,
                    "PROFILE_TL_L2P5_HD_VALID": 0,
                    "PROFILE_TL_INNER_VLAN_TAG": 0,
                    "PROFILE_TL_OUT_VLAN_TAG": 0,
                    "PROFILE_TL_MAC_TYPE": 0,
                    "PROFILE_TL_L2_HD_VALID": 0,
                    "PROFILE_OT_L5P5_HD_TYPE": 0,
                    "PROFILE_OT_L5P5_HD_VALID": 0,
                    "PROFILE_OT_TUNNEL_FLAGS": 0,
                    "PROFILE_OT_TUNNEL_TYPE": 0,
                    "PROFILE_OT_TUNNEL_VALID": 0,
                    "PROFILE_OT_L4_IS_TCPUDP": 0,
                    "PROFILE_OT_L4_HD_TYPE": 0,
                    "PROFILE_OT_L4_HD_VALID": 0,
                    "PROFILE_OT_L3P5_HD_TYPE": 0,
                    "PROFILE_OT_L3P5_VALID": 0,
                    "PROFILE_OT_L3_IS_IP": 0,
                    "PROFILE_OT_L3_HD_TYPE": 0,
                    "PROFILE_OT_L3_HD_VALID": 0,
                    "PROFILE_OT_L2P5_SUBTYPE": 0,
                    "PROFILE_OT_L2P5_HD_TYPE": 0,
                    "PROFILE_OT_L2P5_HD_VALID": 0,
                    "PROFILE_OT_INNER_VLAN_TAG": 0,
                    "PROFILE_OT_OUT_VLAN_TAG": 0,
                    "PROFILE_OT_MAC_TYPE": 0,
                    "PROFILE_OT_L2_HD_VALID": 0,
                    "PROFILE_RSV": 0,
                    "PROFILE_PIPE_ID": 0
                },
                "mask": {
                    "PROFILE_GROUP_INDEX": 0,
                    "PROFILE_KEY_BUILD_PROFILE_ID": 0,
                    "PROFILE_L4_DST_PORT": 0,
                    "PROFILE_L4_IS_TCPUDP": 0,
                    "PROFILE_L4_HD_TYPE": 0,
                    "PROFILE_L4_HD_VALID": 0,
                    "PROFILE_L3P5_HD_TYPE": 0,
                    "PROFILE_L3P5_VALID": 0,
                    "PROFILE_L3_IS_IP": 0,
                    "PROFILE_L3_HD_TYPE": 0,
                    "PROFILE_L3_HD_VALID": 0,
                    "PROFILE_L2P5_SUBTYPE": 0,
                    "PROFILE_L2P5_HD_TYPE": 0,
                    "PROFILE_L2P5_HD_VALID": 0,
                    "PROFILE_INNER_VLAN_TAG": 0,
                    "PROFILE_OUT_VLAN_TAG": 0,
                    "PROFILE_MAC_TYPE": 0,
                    "PROFILE_L2_HD_VALID": 0,
                    "PROFILE_TL_L5P5_HD_TYPE": 0,
                    "PROFILE_TL_L5P5_HD_VALID": 0,
                    "PROFILE_TL_TUNNEL_FLAGS": 0,
                    "PROFILE_TL_TUNNEL_TYPE": 0,
                    "PROFILE_TL_TUNNEL_VALID": 0,
                    "PROFILE_TL_L4_IS_TCPUDP": 0,
                    "PROFILE_TL_L4_HD_TYPE": 0,
                    "PROFILE_TL_L4_HD_VALID": 0,
                    "PROFILE_TL_L3P5_HD_TYPE": 0,
                    "PROFILE_TL_L3P5_VALID": 0,
                    "PROFILE_TL_L3_IS_IP": 0,
                    "PROFILE_TL_L3_HD_TYPE": 0,
                    "PROFILE_TL_L3_HD_VALID": 0,
                    "PROFILE_TL_L2P5_SUBTYPE": 0,
                    "PROFILE_TL_L2P5_HD_TYPE": 0,
                    "PROFILE_TL_L2P5_HD_VALID": 0,
                    "PROFILE_TL_INNER_VLAN_TAG": 0,
                    "PROFILE_TL_OUT_VLAN_TAG": 0,
                    "PROFILE_TL_MAC_TYPE": 0,
                    "PROFILE_TL_L2_HD_VALID": 0,
                    "PROFILE_OT_L5P5_HD_TYPE": 0,
                    "PROFILE_OT_L5P5_HD_VALID": 0,
                    "PROFILE_OT_TUNNEL_FLAGS": 0,
                    "PROFILE_OT_TUNNEL_TYPE": 0,
                    "PROFILE_OT_TUNNEL_VALID": 0,
                    "PROFILE_OT_L4_IS_TCPUDP": 0,
                    "PROFILE_OT_L4_HD_TYPE": 0,
                    "PROFILE_OT_L4_HD_VALID": 0,
                    "PROFILE_OT_L3P5_HD_TYPE": 0,
                    "PROFILE_OT_L3P5_VALID": 0,
                    "PROFILE_OT_L3_IS_IP": 0,
                    "PROFILE_OT_L3_HD_TYPE": 0,
                    "PROFILE_OT_L3_HD_VALID": 0,
                    "PROFILE_OT_L2P5_SUBTYPE": 0,
                    "PROFILE_OT_L2P5_HD_TYPE": 0,
                    "PROFILE_OT_L2P5_HD_VALID": 0,
                    "PROFILE_OT_INNER_VLAN_TAG": 0,
                    "PROFILE_OT_OUT_VLAN_TAG": 0,
                    "PROFILE_OT_MAC_TYPE": 0,
                    "PROFILE_OT_L2_HD_VALID": 0,
                    "PROFILE_RSV": 0,
                    "PROFILE_PIPE_ID": 0
                },
                "table": {
                    "PROFILE_KEY_BUILD_OP_CODE": 4,
                    "PROFILE_DEF_ACT_IDX": 0,
                    "PROFILE_MEP_DSTR_PROF": 0,
                    "PROFILE_MEP_DSPATCH_TYPE": 0,
                    "PROFILE_DEFAULT_DEST_VALID": 0,
                    "PROFILE_ACT_TYPE": 0,
                    "PROFILE_DEFAULT_DEST": 0,
                    "PROFILE_EM_LK_ENABLE": 0,
                    "PROFILE_EM_LK_PROF_ID": 0,
                    "PROFILE_EM_LK_KEY_ID": 0,
                    "PROFILE_EM_TBL_ID": 0,
                    "PROFILE_EM_KEY_LEN": 0,
                    "PROFILE_WC_LK_ENABLE": 0,
                    "PROFILE_WC_LK_PROF_ID": 0,
                    "PROFILE_WC_LK_KEY_ID": 0,
                    "PROFILE_WC_KEY_LEN": 0,
                    "PROFILE_SET_TC_ENABLE": 0,
                    "PROFILE_SET_TC_VALUE": 0,
                    "PROFILE_EM_TCP_FLAG_POLICY": 0
                }
            },
            "register" : {
                "tbl_name": "register",
                "tbl_pipe": 0,
                "key": {
                    "REG_TYPE": 0,
                    "REG_ID": 0
                },
                "table": {
                    "REG_VALUE": 0
                }
            },
            "key_mask" : {
                "tbl_name": "key_mask",
                "tbl_pipe": 0,
                "key": {
                    "KEY_MASK_INDEX": 1
                },
                "table": {
                    "KEY_MASK1_L": 0,
                    "KEY_MASK1_H": 0,
                    "KEY_MASK2_L": 0,
                    "KEY_MASK2_H": 0,
                    "KEY_MASK3_L": 0,
                    "KEY_MASK3_H": 0,
                    "KEY_MASK4_L": 0,
                    "KEY_MASK4_H": 0,
                    "KEY_MASK5_L": 0,
                    "KEY_MASK5_H": 0,
                    "KEY_MASK6_L": 0,
                    "KEY_MASK6_H": 0,
                    "KEY_MASK7_L": 0,
                    "KEY_MASK7_H": 0,
                    "KEY_MASK8_L": 0,
                    "KEY_MASK8_H": 0,
                    "KEY_MASK9_L": 0,
                    "KEY_MASK9_H": 0,
                    "KEY_MASK10_L": 0,
                    "KEY_MASK10_H": 0,
                    "KEY_MASK11_L": 0,
                    "KEY_MASK11_H": 0,
                    "KEY_MASK12_L": 0,
                    "KEY_MASK12_H": 0
                }
            },
            "key_template" : {
                "tbl_name": "key_template",
                "tbl_id": 0,
                "tbl_pipe": 0,
                "key": {
                    "KEY_TEMPLATE_INDEX": 12
                },
                "table": {
                    "KEY_TEMPLATE_KEY_PROF_ID": 0,
                    "KEY_TEMPLATE_GROUP_IDX": 0,
                    "KEY_TEMPLATE_VNIC_ID": 0,
                    "KEY_TEMPLATE_META_DATA": 0,
                    "KEY_TEMPLATE_MAC_PORT_ENABLE": 0,
                    "KEY_TEMPLATE_OT_L2_DMAC": 0,
                    "KEY_TEMPLATE_OT_L2_SMAC": 0,
                    "KEY_TEMPLATE_OT_L2_OUT_VLAN_TPID": 0,
                    "KEY_TEMPLATE_OT_L2_OUT_VLAN_PRI": 0,
                    "KEY_TEMPLATE_OT_L2_OUT_VLAN_DE": 0,
                    "KEY_TEMPLATE_OT_L2_OUT_VLAN_VID": 0,
                    "KEY_TEMPLATE_OT_L2_INNER_VLAN_TPID": 0,
                    "KEY_TEMPLATE_OT_L2_INNER_VLAN_PRI": 0,
                    "KEY_TEMPLATE_OT_L2_INNER_VLAN_DE": 0,
                    "KEY_TEMPLATE_OT_L2_INNER_VLAN_VID": 0,
                    "KEY_TEMPLATE_OT_L3_TYPE": 0,
                    "KEY_TEMPLATE_OT_L3_SIP": 0,
                    "KEY_TEMPLATE_OT_L3_DIP": 0,
                    "KEY_TEMPLATE_OT_L3_PROT": 0,
                    "KEY_TEMPLATE_OT_L3_TTL": 0,
                    "KEY_TEMPLATE_OT_L3_TOS": 0,
                    "KEY_TEMPLATE_OT_L3_FLOW": 0,
                    "KEY_TEMPLATE_OT_L3_FRAG": 0,
                    "KEY_TEMPLATE_OT_L3_EXT_HD_VALID": 0,
                    "KEY_TEMPLATE_OT_L4_SPORT1": 0,
                    "KEY_TEMPLATE_OT_L4_SPORT2": 0,
                    "KEY_TEMPLATE_OT_L4_DPORT": 0,
                    "KEY_TEMPLATE_OT_L4_FLAGS": 0,
                    "KEY_TEMPLATE_OT_TUNNEL_TYPE": 0,
                    "KEY_TEMPLATE_OT_TUNNEL_ID": 0,
                    "KEY_TEMPLATE_OT_TUNNEL_FLAGS": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_FLAGS": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_TTL": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_LEN": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_MD_TYPE": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_NEXT_PROT": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_SPI": 0,
                    "KEY_TEMPLATE_OT_L5P5_NSH_SI": 0,
                    "KEY_TEMPLATE_TL_L2_DMAC": 0,
                    "KEY_TEMPLATE_TL_L2_SMAC": 0,
                    "KEY_TEMPLATE_TL_L2_OUT_VLAN_TPID": 0,
                    "KEY_TEMPLATE_TL_L2_OUT_VLAN_PRI": 0,
                    "KEY_TEMPLATE_TL_L2_OUT_VLAN_DE": 0,
                    "KEY_TEMPLATE_TL_L2_OUT_VLAN_VID": 0,
                    "KEY_TEMPLATE_TL_L2_INNER_VLAN_TPID": 0,
                    "KEY_TEMPLATE_TL_L2_INNER_VLAN_PRI": 0,
                    "KEY_TEMPLATE_TL_L2_INNER_VLAN_DE": 0,
                    "KEY_TEMPLATE_TL_L2_INNER_VLAN_VID": 0,
                    "KEY_TEMPLATE_TL_L3_TYPE": 0,
                    "KEY_TEMPLATE_TL_L3_SIP": 0,
                    "KEY_TEMPLATE_TL_L3_DIP": 0,
                    "KEY_TEMPLATE_TL_L3_PROT": 0,
                    "KEY_TEMPLATE_TL_L3_TTL": 0,
                    "KEY_TEMPLATE_TL_L3_TOS": 0,
                    "KEY_TEMPLATE_TL_L3_FLOW": 0,
                    "KEY_TEMPLATE_TL_L3_FRAG": 0,
                    "KEY_TEMPLATE_TL_L3_EXT_HD_VALID": 0,
                    "KEY_TEMPLATE_TL_L4_SPORT1": 0,
                    "KEY_TEMPLATE_TL_L4_SPORT2": 0,
                    "KEY_TEMPLATE_TL_L4_DPORT": 0,
                    "KEY_TEMPLATE_TL_L4_FLAGS": 0,
                    "KEY_TEMPLATE_TL_TUNNEL_TYPE": 0,
                    "KEY_TEMPLATE_TL_TUNNEL_ID": 0,
                    "KEY_TEMPLATE_TL_TUNNEL_FLAGS": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_FLAGS": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_TTL": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_LEN": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_MD_TYPE": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_NEXT_PROT": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_SPI": 0,
                    "KEY_TEMPLATE_TL_L5P5_NSH_SI": 0,
                    "KEY_TEMPLATE_L2_DMAC": 0,
                    "KEY_TEMPLATE_L2_SMAC": 0,
                    "KEY_TEMPLATE_L2_OUT_VLAN_TPID": 0,
                    "KEY_TEMPLATE_L2_OUT_VLAN_PRI": 0,
                    "KEY_TEMPLATE_L2_OUT_VLAN_DE": 0,
                    "KEY_TEMPLATE_L2_OUT_VLAN_VID": 0,
                    "KEY_TEMPLATE_L2_INNER_VLAN_TPID": 0,
                    "KEY_TEMPLATE_L2_INNER_VLAN_PRI": 0,
                    "KEY_TEMPLATE_L2_INNER_VLAN_DE": 0,
                    "KEY_TEMPLATE_L2_INNER_VLAN_VID": 0,
                    "KEY_TEMPLATE_L3_TYPE": 0,
                    "KEY_TEMPLATE_L3_SIP": 0,
                    "KEY_TEMPLATE_L3_DIP": 0,
                    "KEY_TEMPLATE_L3_PROT": 0,
                    "KEY_TEMPLATE_L3_TTL": 0,
                    "KEY_TEMPLATE_L3_TOS": 0,
                    "KEY_TEMPLATE_L3_FLOW": 0,
                    "KEY_TEMPLATE_L3_FRAG": 0,
                    "KEY_TEMPLATE_L3_EXT_HD_VALID": 0,
                    "KEY_TEMPLATE_L4_SPORT1": 0,
                    "KEY_TEMPLATE_L4_SPORT2": 0,
                    "KEY_TEMPLATE_L4_DPORT": 0,
                    "KEY_TEMPLATE_L4_FLAGS": 0,
                    "KEY_TEMPLATE_UDF0_EN": 0,
                    "KEY_TEMPLATE_UDF0_SEL": 0,
                    "KEY_TEMPLATE_UDF1_EN": 0,
                    "KEY_TEMPLATE_UDF1_SEL": 0,
                    "KEY_TEMPLATE_UDF2_EN": 0,
                    "KEY_TEMPLATE_UDF2_SEL": 0,
                    "KEY_TEMPLATE_UDF3_EN": 0,
                    "KEY_TEMPLATE_UDF3_SEL": 0,
                    "KEY_TEMPLATE_UDF4_EN": 0,
                    "KEY_TEMPLATE_UDF4_SEL": 0,
                    "KEY_TEMPLATE_UDF5_EN": 0,
                    "KEY_TEMPLATE_UDF5_SEL": 0,
                    "KEY_TEMPLATE_UDF6_EN": 0,
                    "KEY_TEMPLATE_UDF6_SEL": 0,
                    "KEY_TEMPLATE_UDF7_EN": 0,
                    "KEY_TEMPLATE_UDF7_SEL": 0,
                    "KEY_TEMPLATE_RANGE_CHECK_TYPE0": 0,
                    "KEY_TEMPLATE_RANGE_CHECK_TYPE1": 0
                }
            },
            "em_table" : {
                "tbl_name":"em_table",
                "tbl_id": 0,
                "key_len": 0,
                "key": [0]*24,
                "table":{
                    "PRIORITY":  0,
                    "VERSION0":  0,
                    "VERSION1":  0,
                    "VERSION2":  0,
                    "VERSION3":  0,
                    "VER_GROUP0":  0,
                    "VER_GROUP1":  0,
                    "VER_GROUP2":  0,
                    "VER_GROUP3":  0,
                    "RANG_INDEX0":  0,
                    "RANG_INDEX1":  0,
                    "STATS_SAME_IDX":  0,
                    "STATISTICS":  0,
                    "CMD_QUEUE_ID":  0,
                    "AGE_MOD":  0,
                    "ECMP_ENABLE":  0,
                    "ECMP_ENTRY_NUM":  0,
                    "TSE_RSV":  0,
                    "EX_RESULT_INDEX":  0,
                    "TSE_EXT_RESULT_LEN":  0,
                    "PIPE_EXT_RESULT_LEN":  0,
                    "OPCODE":  0,
                    "KEYBUILD_PROFILE_ID":  0,
                    "STORAGE_READ":  0,
                    "GROUP_STATS_INDEX":  0,
                    "MEP_DISTRI_PROF":  0,
                    "MEP_DISPATCH_TYPE":  0,
                    "SOURCE_TABLE":  10,
                    "SET_TC_ENABLE":  0,
                    "SET_TC_VALUE":  0,
                    "DESTINATION_VALID":  0,
                    "ACTION_TYPE":  0,
                    "DESTINATION":  0,
                    "DECAPSULATION":  0,
                    "MIRROR_PRI":  0,
                    "MIRROR_METER_INDEX":  0,
                    "MIRRORING":  0,
                    "EXT_BIT_MAP":  0,
                    "METER_NUM":  0,
                    "METADATA_UPDATE":  0,
                    "REPLACE_L4_DPORT":  0,
                    "REPLACE_L4_SPORT":  0,
                    "REPLACE_DIPV4":  0,
                    "REPLACE_SIPV4":  0,
                    "REPLACE_DIPV6":  0,
                    "REPLACE_SIPV6":  0,
                    "TTL_UPDATE":  0,
                    "TOS_UPDATE":  0,
                    "REMOVE_OUTER_VLAN":  0,
                    "REMOVE_INNER_VLAN":  0,
                    "REPLACE_INNER_VLAN":  0,
                    "REPLACE_OUTER_VLAN":  0,
                    "REPLACE_SMAC":  0,
                    "REPLACE_DMAC":  0,
                    "DEC_NSH_TTL":  0,
                    "INT_TUNNEL_DELETE":  0,
                    "UPDATE_FIELD":  0,
                    "TUNNEL_ENCAP_TYPE":  0,
                    "TUNNEL_ENCAP_LEN":  0,
                    "L4_ENCAP_TYPE":  0,
                    "L3_ENCAP_TYPE":  0,
                    "VTAG_TYPE":  0,
                    "L2_FLAG":  0,
                    "ECN_INHERIT_TO_INNER":  0,
                    "ECN_INHERIT_TO_OUTER":  0,
                    "RSV":  0,
                    "data":[]
                }
            }
        }
    def get(self):
        return self.value
    




